### ISSUE TITLE
deno install failed

### ISSUE THREAD

**Issue by anylayer** [wydengyre/pgs-to-srt#250]
error: Uncaught SyntaxError: missing ) after argument list
    at file:///root/pgs-to-srt/pgs-to-srt.js:2:26346

**Comment by wydengyre** [comment]
My apologies. Acknowledging this bug here and will get to it ASAP.

**Comment by wydengyre** [comment]
@anylayer can you send the full command you are using to run?

**Comment by wydengyre** [comment]
Closing this as stale. Will reopen if full command is given. I'm seeking to transition this repo to using node, as well, so this issue will likely go away.
